---
output:
  html_document:
    code_folding: hide
urlcolor: blue
---

```{r child = 'Knitr_setup.Rmd'}
```

# Optimization 

When modelling optimizing and tuning the models is an important task to achieve proper results.
Throughout this report we have deployed various different models and optimized them during modelling within the respective chapters. 

Our documented findings display the final optimized results, some examples for optimization include:

- Linear Models: Selecting relevant predictor variables and deciding whether to use log-transformed versions thereof, to achieve a high model accuracy (e.g. adjusted R-squared).
- GAMs: Selecting relevant predictor variables and deciding whether to use log-transformed versions thereof, to achieve a high model accuracy (e.g. adjusted R-squared).
- GLMs: Selecting relevant predictor variables and deciding whether to use log-transformed versions thereof, to achieve a high model accuracy (e.g. Deviance).
- Support Vector machines: Tuning the cost parameter
- Neural networks: Tuning hyperparameters such as the amount of hidden layers.
