---
output:
  html_document:
    code_folding: hide
urlcolor: blue
---

```{r child = 'Knitr_setup.Rmd'}
```

```{r}
library(tidyverse)
library(e1071)
library(caret)
library(knitr)
```

# Support vector machine (SVM)
```{r}
col_classes <- c(Release.date = "Date")
games <- read.csv('data/games_clean.csv', colClasses = col_classes)
```

## Predicting revenue

```{r}
features <- c("Peak.CCU.log", "Metacritic.score", "Positive.log", "Negative.log", "Publishers.count",
              "Genre.Indie", "Genre.Action", "Genre.Adventure", "Genre.Simulation", "Genre.Strategy")
games_Xy <- games[, c(features, "Revenue.log")]

# Replace NA values with 0
# df[features] <- lapply(df[features], function(x) replace(x, is.na(x), 0))

games_Xy <- na.omit(games_Xy)  # Remove rows with NA values
```

```{r}
set.seed(42)
indices <- createDataPartition(games_Xy$Revenue.log, p = .85, list = F)
train <- games_Xy[indices,]
test <- games_Xy[-indices,]
```

```{r}
grid <- expand.grid(C = c(0.01, 0.1, 1, 10))
trctrl <- trainControl(method = "repeatedcv", number = 5, repeats = 1)

games_svm <- train(
    Revenue.log ~ ., data = train, method = "svmLinear",
    trControl = trctrl,
    preProcess = c("center", "scale"),
    tuneGrid = grid
)
plot(games_svm)

games_svm
```

```{r}
pred <- predict(games_svm, test)
plot(test$Revenue.log, pred, xlab = "Actual", ylab = "Predicted", main = "Revenue (log) - Actual vs Predicted")
abline(lm(pred ~ test$Revenue.log), 1, col = "red")

mse <- mean((test$Revenue.log - pred)^2)
mae <- MAE(test$Revenue.log, pred)
rmse <- RMSE(test$Revenue.log, pred)
r2 <- R2(test$Revenue.log, pred, form <- "traditional")

cat(" MAE:", mae, "\n", "MSE:", mse, "\n",
    "RMSE:", rmse, "\n", "R-squared:", r2, "\n")
```

## Indie game classification
```{r}
features <- c("Revenue.log", "Owners.mean", "Peak.CCU.log", "Metacritic.score", "Positive.log", "Negative.log", "Publishers.count")
indie_Xy <- games[, c(features, "Genre.Indie")]
indie_Xy$Genre.Indie <- as.factor(indie_Xy$Genre.Indie)

indie_Xy <- na.omit(indie_Xy)  # Remove rows with NA values

indie_stats <- indie_Xy %>%
    group_by(Genre.Indie) %>%
    summarise("Count" = n(), "Revenue" = round(mean(exp(Revenue.log))), "Owners" = round(mean(Owners.mean)),
              "Metacritic Score" = round(mean(`Metacritic.score`)),
              "Peak CCU" = round(mean(exp(Peak.CCU.log))), "Positive Votes" = round(mean(exp(Positive.log))),
              "Negative Votes" = round(mean(exp(Negative.log))), "Publisher count" = round(mean(Publishers.count)))

kable(indie_stats)
```
```{r}
set.seed(42)
indices <- createDataPartition(indie_Xy$Genre.Indie, p = .85, list = F)
train <- indie_Xy[indices,]
test <- indie_Xy[-indices,]

trctrl <- trainControl(method = "repeatedcv", number = 5, repeats = 1)

indie_svm <- train(Genre.Indie ~ ., data = train, method = "svmLinear",
                    trControl = trctrl,
                    preProcess = c("center", "scale"))

indie_svm
```
```{r}
# Apply to Test Data
test_pred <- predict(indie_svm, newdata = test)
confusionMatrix(table(test_pred, test$Genre.Indie))
```

